services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    image: $DOCKER_USERNAME/nextjs-app-world-football
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      URL_API: ${URL_API}
      VERSION: ${VERSION}
      API_KEY: ${API_KEY}
    volumes:
      - .:/app
