version: '3'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      URL_API: ${URL_API}
      VERSION: ${VERSION}
      API_TOKEN: ${API_TOKEN}
    volumes:
      - .:/app