name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-to-dockerhub:
    # Este job depende del job "build" del archivo "node.js.yml"
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nextjs-project-dev-ops:latest
          build-args:
            #NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
            API_URL: ${{ secrets.API_URL }}
            VERSION: ${{ secrets.VERSION }}
            API_KEY: ${{ secrets.API_KEY }}

      - name: Deploy to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nextjs-project-dev-ops:latest
