name: DevOps-usfx CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Create .env.production
        run: |
          echo "URL_API=${{ secrets.URL_API }}" > .env.production
          echo "VERSION=${{ secrets.VERSION }}" >> .env.production
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env.production

      - run: npm install
      - run: npm run lint
      - run: npm run build --if-present

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env.production
        run: |
          echo "URL_API=${{ secrets.URL_API }}" > .env.production
          echo "VERSION=${{ secrets.VERSION }}" >> .env.production
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env.production

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile 
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nextjs-project-dev-ops:latest
