name: DevOps-usfx CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Create .env.production
      run: |
        echo "URL_API=${{ secrets.URL_API }}" >> .env.production
        echo "VERSION=${{ secrets.VERSION }}" >> .env.production
        echo "API_KEY=${{ secrets.API_KEY }}" >> .env.production

    - run: npm install
    - run: npm run lint
    - run: npm run build --if-present
